/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An Atom 1.0 feed model used before RFC 4287 XML serialization.
 */
export interface AtomFeed {
  id: string
  title: AtomTextConstruct
  updated: string
  /**
   * The feed language serialized as xml:lang.
   */
  language?: string
  /**
   * @minItems 1
   */
  author?: [AtomPerson, ...AtomPerson[]]
  link?: AtomLink[]
  generator?: AtomGenerator
  icon?: string
  logo?: string
  rights?: string
  subtitle?: string
  entry?: AtomEntry[]
}
export interface AtomTextConstruct {
  value: string
  type?: 'text' | 'html' | 'xhtml'
}
export interface AtomPerson {
  name: string
  email?: string
  uri?: string
}
export interface AtomLink {
  href: string
  rel?: string
  type?: string
  hreflang?: string
  title?: string
  length?: number
}
export interface AtomGenerator {
  value?: string
  uri?: string
  version?: string
}
export interface AtomEntry {
  id: string
  title: AtomTextConstruct
  updated: string
  published?: string
  /**
   * The entry language serialized as xml:lang.
   */
  language?: string
  /**
   * @minItems 1
   */
  author?: [AtomPerson, ...AtomPerson[]]
  content?: AtomContent
  summary?: AtomTextConstruct
  link?: AtomLink[]
  category?: AtomCategory[]
}
export interface AtomContent {
  value?: string
  type?: string
  src?: string
}
export interface AtomCategory {
  term: string
  scheme?: string
  label?: string
}
